# Generated by Django 5.0b1 on 2023-12-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0005_userbot_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200, verbose_name='Target')),
                ('in_process', models.BooleanField(default=False)),
                ('bots', models.ManyToManyField(to='bots.userbot')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('sleep', models.PositiveIntegerField(verbose_name='Sleep')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
