# Generated by Django 5.0b1 on 2023-12-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_task_bots_banned_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bots_banned',
            field=models.IntegerField(default=0, verbose_name='Bots banned'),
        ),
    ]
