# Generated by Django 5.0b1 on 2023-12-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_task_bots_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bots_banned',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
