# Generated by Django 5.0b1 on 2023-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_task_bots_banned_remove_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bots_banned',
            field=models.IntegerField(default=0, verbose_name='Bots banned'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
