# Generated by Django 5.0b1 on 2023-12-14 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_userbot_created_date_userbot_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
            ],
            options={
                'managed': False,
            },
        ),
    ]
