# Generated by Django 5.0b1 on 2023-12-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_userbotupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBotUpload',
        ),
    ]
