# Generated by Django 5.0b1 on 2023-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_userbot_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Free'),
        ),
    ]
