# Generated by Django 5.0b1 on 2023-12-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_userbot_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
