# Generated by Django 5.0b1 on 2023-12-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_userbot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbot',
            name='unban_date',
        ),
    ]
