# Generated by Django 5.0b1 on 2023-12-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_remove_userbot_unban_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='country',
            field=models.CharField(choices=[('ID', 'Indonesia'), ('US', 'United States of America')], default='US', max_length=200, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
