# Generated by Django 5.0b1 on 2023-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_userbot_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='proxy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proxy'),
        ),
    ]
