# Generated by Django 5.0b1 on 2023-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_remove_userbot_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='proxy',
            field=models.JSONField(blank=True, null=True, verbose_name='Proxy'),
        ),
    ]
