# Generated by Django 5.0b1 on 2023-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_userbot_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='proxy_string',
            field=models.CharField(blank=True, null=True, verbose_name='Proxy string'),
        ),
    ]
